### ISSUE TITLE
Credit for Liquibase Extension

### ISSUE THREAD

**Issue by molivasdat** [liquibase/liquibase-spanner#1]
**Issue:**  This issue is solely for giving credit for Legends Program Liquibase Extension

**Creditor:** @mescanne
**Name:** Mark Scannel

Hi @mescanne  If you can comment on this issue, I can assign it to you and give you credit for creating this extension for the Legends program.

**Comment by jimmyruska** [comment]
All credit is to Mark Scannell, Knut Olav Løite . No credit for me, thanks. I've been working on some private extension work

**Comment by molivasdat** [comment]
Thanks for the response and update.  I'll change it to Mark and Knut.

**Comment by mescanne** [comment]
Commented! Knut was also instrumental for the bulk of the extension.

**Comment by molivasdat** [comment]
Giving him credit too!
