### ISSUE TITLE
Credit for Liquibase Extension

### ISSUE THREAD

**Issue by molivasdat** [liquibase/liquibase-spanner#2]
**Issue:** This issue is solely for giving credit for Legends Program Liquibase Extension

**Creditor:** @olavloite
**Name:** Knut Olav Løite

Hi @olavloite If you can comment on this issue, I can assign it to you and give you credit for creating this extension for Liquibase and Spanner.  We want to recognize the effort you have put in for creating this extension.  We appreciate it.

**Comment by olavloite** [comment]
@molivasdat Thanks for reaching out to me and wanting to give me credit. It should be noted though that I worked on it together with @mescanne.

**Comment by molivasdat** [comment]
Thanks @olavloite I am giving him credit as well.  Just doing it with an issue apiece.
